### ISSUE TITLE
Butos bootloader not working on real computers

### ISSUE THREAD

**Issue by FrancescoLFM** [FrancescoLFM/butos#4]
Butos won't load on real computers that emulate usb sticks as hard drives, because the bios doesn't recognize the unformatted mbr... Also the bootloader uses floppy CHS geometry to read the other sectors of the usb stick, that's not correct and should be fix.

**Comment by LoZack19** [comment]
So you now get to decide what's a "real computer" and what isn't? I can 100% assure you that PowerTrattore was much more real than your nvidia+inter-powered computer de mei coioni 

![image](https://user-images.githubusercontent.com/71092108/212076272-eac67bc9-5b36-4499-ac3b-88cee28bdd4b.png)

**Comment by LoZack19** [comment]
Memes aside, I don't think that the CHS geometry is a problem. I think that the USB can be read as a normal disk. In fact on my old laptop the fact that I booted from a usb stick didn't create any problems to the bios `int 0x13`

**Comment by FrancescoLFM** [comment]
The problem isn't the chs geometry, but how the bootloader deals with, it assumes that the drive is a floppy, but on modern computers, flash sticks are emulated as hard disks.
To fix the problem drive_number value (init.s) should be changed from 0x00 (floppy) to 0x80 (hard disk)
https://stanislavs.org/helppc/int_13-2.html

**Comment by LoZack19** [comment]
AAAAAAH in that sense. Probabily yes. Mhhh, or maybe we should try both to consider every possible scenario. Idk, we could also ignore old computers and concentrate on new ones, but it would be cool to support both options.

**Comment by FrancescoLFM** [comment]
Already resolved when mbr was implemented.
